### ISSUE TITLE
No outside temp and current water heater temp.

### ISSUE THREAD

**Issue by VoyteckPL** [chomupashchuk/ariston-remotethermo-home-assistant#1]
Hi! Great integration but these 2 values are missing. If I can help, just let me know!
https://i.postimg.cc/J4MqgFcm/heater.png

**Comment by VoyteckPL** [comment]
Just to let you know, it's available in this integration:

https://github.com/julupanter/homeassistant-ariston-sensor

Maybe you could add it?

**Comment by chomupashchuk** [comment]
I'll have a look and can try including sensors. The problem is that those specific sensors do not work for my hardware (unsupported values shown, as for example I use openweathermap within ariston rather than actual hardware outdoor sensor and I get temp 3276). Initially I added what works for me as I'm not sure if it works for others, as ariston api often gives some strange data (holiday mode in my case changes temperature to antifreeze and keeps holiday as false).
You may also uncomment storing in json file within __ini__ (and create \tmp folder with full access within \config). It might be good to see what valid data is available for your config.
You may share what data is valid in your case (what part of json/dictionary corresponds to it) and what you'd like to have within integration.

**Comment by chomupashchuk** [comment]
I have added:
binary_sensor "heat_pump"
sensors "dhw_storage_temperature" and "outside_temperature"

Please check if they work in you configuration.

I suspect that outside temperature depends on external hardware sensor connected to boiler, which i do not have.
DHW storage temperature is not supported by my boiler and heating pump always shows "false" for my boiler regardless of what it is doing.

**Comment by chomupashchuk** [comment]
By the way, hows weather in Poland? Rainy as in Ukraine?

**Comment by VoyteckPL** [comment]
Hi! First off all thanks for a really quick reaction! 
Weather is awful... cold and wet haha. Same as Ukraine, I guess :)
My setup is:

Ariston Genus One System 24
120L Ariston Heater
Cube Thermostat

The temperature in Ariston App is taken from OpenWeatherMap as they claim. I don't have hardware sensor. 

Ok so it works!
I had to add these 2 as separate sensors by adding this in configuration.yaml:

ariston:
  username: xxxx
  password: xxxx
  sensors:
    - dhw_storage_temperature
    - outside_temperature

There is one problem, I hope I can explain it.
When I add water_heater.ariston in lovelace as entities and I click it to view a graph of temperature I can only see a graph of the temperature I would like to achieve. I don't see the temperature "dhw_storage_temperature" as it is e separate sensor.
I suppose you should somehow put dhw_storage_temperature as an attribute of water_heater.ariston?
Maybe do the same for the outside temperature (also for climate.ariston)?

Great work, I'm so happy I don't have to use applehomekit integration :)

**Comment by VoyteckPL** [comment]
https://i.postimg.cc/nhYPNR2M/image823.png

**Comment by chomupashchuk** [comment]
I tried different things, but it seems like it is default setting of climate to show "set" temperature.
Also i tried to include attributes in climate, but it did not work.

I have added DHW storage temperature in water_heater at least.

The only documentation i have to work with (and i did not find any tips in examples to help):
https://developers.home-assistant.io/docs/entity_water_heater
https://developers.home-assistant.io/docs/entity_climate

I use Grafana and InfluxDB to generate graphs of states to not use built-in history (which is rather limited). Grafana allows to add multiple sensors on one graph, select duration etc.
https://i.postimg.cc/6qQmKp0s/Capture.png
And if you use generic_camera, you may add images from grafana in Home Assistant (stupid approach, but at least it works).

**Comment by chomupashchuk** [comment]
This and many other sensors are added. But it not an issue :)
